import { CMAService } from './cma.js';
import { logger } from '../utils/logger.js';
import * as fs from 'fs';
import * as path from 'path';

/**
 * CMA PDF Generation Service
 * Generates PDF reports for CMA requests
 * 
 * Note: This is a basic implementation. For production, consider using:
 * - pdfkit (lightweight, programmatic)
 * - puppeteer (renders HTML to PDF, more flexible)
 * - @react-pdf/renderer (if using React components)
 */
export class CMAPDFService {
  /**
   * Generate PDF for a CMA request
   * Returns the file path or URL where the PDF is stored
   */
  static async generatePDF(
    cmaId: string,
    slackUserId: string,
    outputDir: string = './cma-pdfs'
  ): Promise<string> {
    logger.info('Generating CMA PDF', { cmaId, slackUserId });

    try {
      // Get CMA data
      const cma = await CMAService.getCMARequest(cmaId, slackUserId);
      if (!cma || cma.status !== 'completed') {
        throw new Error(`CMA not found or not completed: ${cmaId}`);
      }

      // Ensure output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      // Generate PDF filename
      const filename = `cma-${cmaId}.pdf`;
      const filepath = path.join(outputDir, filename);

      // For now, generate a simple text-based PDF
      // In production, use pdfkit or puppeteer for proper PDF generation
      const pdfContent = this.generatePDFContent(cma);

      // Write to file (this is a placeholder - in production, use actual PDF library)
      // For now, we'll create an HTML file that can be converted to PDF
      const htmlContent = this.generateHTMLContent(cma);
      const htmlPath = filepath.replace('.pdf', '.html');
      fs.writeFileSync(htmlPath, htmlContent);

      logger.info('CMA PDF generated', { cmaId, filepath: htmlPath });

      // Return the file path
      // In production, convert HTML to PDF using puppeteer or similar
      return htmlPath;
    } catch (error) {
      logger.error('Failed to generate CMA PDF', { cmaId }, error instanceof Error ? error : undefined);
      throw error;
    }
  }

  /**
   * Generate PDF content (text format - placeholder)
   */
  private static generatePDFContent(cma: any): string {
    const estimatedValue = cma.estimatedValue as { low: number; mid: number; high: number } | null;
    
    let content = `COMPARATIVE MARKET ANALYSIS (CMA)\n`;
    content += `=====================================\n\n`;
    content += `Property Address: ${cma.propertyAddress}\n`;
    content += `Generated: ${cma.generatedAt ? new Date(cma.generatedAt).toLocaleString() : 'N/A'}\n`;
    content += `Data Source: ${cma.dataSource || 'Unknown'}\n\n`;

    if (estimatedValue) {
      content += `ESTIMATED VALUE RANGE\n`;
      content += `-------------------\n`;
      content += `Low:  $${estimatedValue.low.toLocaleString()}\n`;
      content += `Mid:  $${estimatedValue.mid.toLocaleString()}\n`;
      content += `High: $${estimatedValue.high.toLocaleString()}\n\n`;
    }

    if (cma.comps && cma.comps.length > 0) {
      content += `COMPARABLE PROPERTIES (${cma.comps.length})\n`;
      content += `==========================================\n\n`;

      cma.comps.forEach((comp: any, index: number) => {
        content += `${index + 1}. ${comp.address}\n`;
        if (comp.salePrice) {
          content += `   Sold: $${parseFloat(comp.salePrice).toLocaleString()}`;
          if (comp.soldDate) {
            content += ` on ${new Date(comp.soldDate).toLocaleDateString()}`;
          }
        } else if (comp.listPrice) {
          content += `   Listed: $${parseFloat(comp.listPrice).toLocaleString()}`;
          if (comp.listDate) {
            content += ` on ${new Date(comp.listDate).toLocaleDateString()}`;
          }
        }
        content += `\n`;
        content += `   ${comp.beds || 'N/A'} bed, ${comp.baths || 'N/A'} bath, ${comp.sqft ? comp.sqft.toLocaleString() : 'N/A'} sqft\n`;
        if (comp.similarityScore) {
          content += `   Similarity: ${(parseFloat(comp.similarityScore) * 100).toFixed(0)}%\n`;
        }
        content += `\n`;
      });
    }

    content += `\n`;
    content += `DISCLAIMER\n`;
    content += `==========\n`;
    content += `This CMA is not an appraisal and is for informational purposes only.\n`;
    content += `Data source: ${cma.dataSource || 'Unknown'}\n`;
    content += `Generated by Slack VA on ${new Date().toLocaleString()}\n`;

    return content;
  }

  /**
   * Generate HTML content (can be converted to PDF)
   */
  private static generateHTMLContent(cma: any): string {
    const estimatedValue = cma.estimatedValue as { low: number; mid: number; high: number } | null;
    
    let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>CMA - ${cma.propertyAddress}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
    h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
    h2 { color: #34495e; margin-top: 30px; }
    .header { margin-bottom: 30px; }
    .value-range { background: #ecf0f1; padding: 20px; border-radius: 5px; margin: 20px 0; }
    .value-item { display: inline-block; margin: 0 20px; }
    .comp { border: 1px solid #bdc3c7; padding: 15px; margin: 10px 0; border-radius: 5px; }
    .comp-header { font-weight: bold; color: #2c3e50; margin-bottom: 10px; }
    .comp-details { color: #7f8c8d; }
    .disclaimer { margin-top: 40px; padding: 20px; background: #fff3cd; border-left: 4px solid #ffc107; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #3498db; color: white; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Comparative Market Analysis (CMA)</h1>
    <p><strong>Property Address:</strong> ${cma.propertyAddress}</p>
    <p><strong>Generated:</strong> ${cma.generatedAt ? new Date(cma.generatedAt).toLocaleString() : 'N/A'}</p>
    <p><strong>Data Source:</strong> ${cma.dataSource || 'Unknown'}</p>
  </div>`;

    if (estimatedValue) {
      html += `
  <div class="value-range">
    <h2>Estimated Value Range</h2>
    <div class="value-item"><strong>Low:</strong> $${estimatedValue.low.toLocaleString()}</div>
    <div class="value-item"><strong>Mid:</strong> $${estimatedValue.mid.toLocaleString()}</div>
    <div class="value-item"><strong>High:</strong> $${estimatedValue.high.toLocaleString()}</div>
  </div>`;
    }

    if (cma.comps && cma.comps.length > 0) {
      html += `
  <h2>Comparable Properties (${cma.comps.length})</h2>
  <table>
    <thead>
      <tr>
        <th>Address</th>
        <th>Price</th>
        <th>Date</th>
        <th>Details</th>
        <th>Similarity</th>
      </tr>
    </thead>
    <tbody>`;

      cma.comps.forEach((comp: any) => {
        const price = comp.salePrice || comp.listPrice;
        const priceLabel = comp.salePrice ? 'Sold' : 'Listed';
        const date = comp.soldDate || comp.listDate;
        const dateStr = date ? new Date(date).toLocaleDateString() : 'N/A';
        const similarity = comp.similarityScore ? `${(parseFloat(comp.similarityScore) * 100).toFixed(0)}%` : 'N/A';

        html += `
      <tr>
        <td>${comp.address}</td>
        <td>$${price ? parseFloat(price).toLocaleString() : 'N/A'}</td>
        <td>${dateStr}</td>
        <td>${comp.beds || 'N/A'} bed, ${comp.baths || 'N/A'} bath, ${comp.sqft ? comp.sqft.toLocaleString() : 'N/A'} sqft</td>
        <td>${similarity}</td>
      </tr>`;
      });

      html += `
    </tbody>
  </table>`;
    }

    html += `
  <div class="disclaimer">
    <h3>Disclaimer</h3>
    <p>This CMA is not an appraisal and is for informational purposes only. Data source: ${cma.dataSource || 'Unknown'}. Generated by Slack VA on ${new Date().toLocaleString()}.</p>
  </div>
</body>
</html>`;

    return html;
  }
}

